{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admiral-rolebinding
  namespace: tasks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admiral-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
{{- end -}}
