apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  labels:
    app: ingress-nginx
    component: ingress
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: '10254'
        prometheus.io/scrape: 'true'
      labels:
        app: ingress-nginx
    spec:
      containers:
      - args:
        - "/nginx-ingress-controller"
        - "--default-backend-service=$(POD_NAMESPACE)/frontend-service"
        - "--default-ssl-certificate=$(POD_NAMESPACE)/ingress-elasticio-cert"
        - "--configmap=$(POD_NAMESPACE)/nginx-configuration"
        - "--tcp-services-configmap=$(POD_NAMESPACE)/tcp-services"
        - "--udp-services-configmap=$(POD_NAMESPACE)/udp-services"
        - "--annotations-prefix=nginx.ingress.kubernetes.io"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.13.0
        imagePullPolicy: IfNotPresent
        name: nginx-ingress-controller
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
