envFromSecretRefName: elasticio

image:
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

rbac:
  create: true

serviceAccount:
  create: true
  name: fluentd-account
