apiVersion: v1
name: frontend
version: "0.1.0"
description: elastic.io frontend
keywords:
  - frontend
home: http://elastic.io
icon: https://elastic.io/wp-content/themes/x-child-onix/images/elastic-red-cloud.svg
maintainers:
  - name: Eugene Obrezkov
    email: ghaiklor@gmail.com
    url: http://ghaiklor.com
engine: gotpl
tillerVersion: ">=2.9.0"
