apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    component: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: elasticio/steward:{{ .Values.image.tag }}
        envFrom:
        - secretRef:
            name: {{ .Values.envFromSecretRefName }}
        env:
        - name: APP_NAME
          value: {{ .Chart.Name }}
        - name: PORT
          value: '3000'
        - name: LOG_LEVEL
          value: trace
        - name: BASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.envFromSecretRefName }}
              key: STEWARD_URI
        - name: STORAGE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.envFromSecretRefName }}
              key: STEWARD_STORAGE_URI
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 3
          httpGet:
            port: 3000
            path: "/"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: false
      imagePullSecrets:
      - name: {{ .Values.image.pullSecretName }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
