apiVersion: apps/v1
kind: Deployment
metadata:
  name: steward
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    component: steward
    app: steward
  annotations:
    deployment.kubernetes.io/revision: '2'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steward
  template:
    metadata:
      name: steward
      labels:
        app: steward
    spec:
      containers:
      - name: steward
        image: 'elasticio/steward:{{ .Values.revision | default "master" }}'
        envFrom:
        - secretRef:
            name: elasticio
        env:
        - name: APP_NAME
          value: steward
        - name: PORT
          value: '3000'
        - name: LOG_LEVEL
          value: trace
        - name: BASE_URL
          valueFrom:
            secretKeyRef:
              name: elasticio
              key: STEWARD_URI
        - name: STORAGE_URL
          valueFrom:
            secretKeyRef:
              name: elasticio
              key: STEWARD_STORAGE_URI
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 3
          httpGet:
            port: 3000
            path: "/"
        resources:
          limits:
            memory: 512Mi
            cpu: 0.5
          requests:
            memory: 256Mi
            cpu: 0.2
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: false
      imagePullSecrets:
      - name: elasticiodevops
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        elasticio-role: '{{ .Release.Namespace }}'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
