apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    component: steward
    app: steward-service
  name: steward-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: '3000'
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: steward
  sessionAffinity: None
  type: NodePort
