replicas: 1
envFromSecretRefName: elasticio

image:
  tag: master
  pullPolicy: Always
  pullSecretName: elasticiodevops

resources:
  limits:
    memory: 512Mi
    cpu: 0.5
  requests:
    memory: 256Mi
    cpu: 0.2

nodeSelector:
  elasticio-role: platform
