apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.claimName }}
spec:
  storageClassName: {{ .Values.volume.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
