apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-storage-slugs-volume-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
