apiVersion: v1
kind: PersistentVolume
metadata:
  name: platform-storage-slugs-volume-westeros
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: slugs-storage-disk-westeros
