apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    component: platform-storage-slugs
    app: platform-storage-slugs-loadbalancer
  annotations:
    cloud.google.com/load-balancer-type: Internal
  name: platform-storage-slugs-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: '{{ .Values.loadBalancerIP }}'
  selector:
    app: platform-storage-slugs
  ports:
  - name: '9999'
    port: 9999
    protocol: TCP
    targetPort: 9999
