apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    component: platform-storage-slugs
    app: platform-storage-slugs-service
  name: platform-storage-slugs-service
spec:
  type: NodePort
  selector:
    app: platform-storage-slugs
  ports:
  - name: '9999'
    port: 9999
    protocol: TCP
    targetPort: 80
