apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitreceiver
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    component: gitreceiver
    app: gitreceiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitreceiver
  template:
    metadata:
      name: gitreceiver
      labels:
        app: gitreceiver
    spec:
      containers:
      - name: gitreceiver
        image: 'elasticio/gitreceiver:{{ .Values.revision | default "master" }}'
        envFrom:
        - secretRef:
            name: elasticio
        env:
        - name: APP_NAME
          value: gitreceiver
        - name: LOG_LEVEL
          value: trace
        - name: APPBUILDER_IMAGE
          value: elasticio/appbuilder:latest
        - name: GIT_BRANCH
          value: master
        - name: WEBDAV_URL
          valueFrom:
            secretKeyRef:
              name: elasticio
              key: SLUG_BASE_URL
        - name: GELF_ADDRESS
          value: "$(GELF_PROTOCOL)://$(GELF_HOST):$(GELF_PORT)"
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 20
          tcpSocket:
            port: 4022
        resources:
          limits:
            memory: 512Mi
            cpu: 0.5
          requests:
            memory: 256Mi
            cpu: 0.1
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-sock
          mountPath: "/var/run/docker.sock"
      volumes:
      - name: docker-sock
        hostPath:
          path: "/var/run/docker.sock"
          type: File
      imagePullSecrets:
      - name: elasticiodevops
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        elasticio-role: '{{ .Release.Namespace }}'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
