apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    component: gitreceiver
    app: gitreceiver-service
  name: gitreceiver-service
  namespace: platform
spec:
  type: NodePort
  selector:
    app: gitreceiver
  ports:
  - name: '4022'
    port: 4022
    protocol: TCP
    targetPort: 4022
