apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    component: gitreceiver
    app: gitreceiver-loadbalancer
  name: gitreceiver-loadbalancer
  namespace: platform
spec:
  type: LoadBalancer
  loadBalancerIP: '{{ .Values.loadBalancerIP }}'
  selector:
    app: gitreceiver
  ports:
  - name: gitreceiver
    port: 22
    protocol: TCP
    targetPort: 4022
