dependencies:
- name: admiral
  version: "~0.1.0"
  repository: "file://../admiral"
- name: api
  version: "~0.1.0"
  repository: "file://../api"
- name: fluentd
  version: "~0.1.0"
  repository: "file://../fluentd"
- name: frontend
  version: "~0.1.0"
  repository: "file://../frontend"
- name: gitreceiver
  version: "~0.1.0"
  repository: "file://../gitreceiver"
- name: ingress
  version: "~0.1.0"
  repository: "file://../ingress"
- name: lookout
  version: "~0.1.0"
  repository: "file://../lookout"
- name: platform-storage-slugs
  version: "~0.1.0"
  repository: "file://../platform-storage-slugs"
- name: scheduler
  version: "~0.1.0"
  repository: "file://../scheduler"
- name: steward
  version: "~0.1.0"
  repository: "file://../steward"
- name: webhooks
  version: "~0.1.0"
  repository: "file://../webhooks"
