apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    component: webhooks
    app: webhooks-service
  name: webhooks-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: '5000'
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: webhooks
  sessionAffinity: None
  type: NodePort
