apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: elasticiodevops
data:
  .dockerconfigjson: '{{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.dockerRegistry (printf "%s:%s" .Values.dockerUsername .Values.dockerPassword | b64enc) | b64enc }}'
