apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: eio-fluentd
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    component: fluentd
    app: eio-fluentd
spec:
  selector:
    matchLabels:
      app: eio-fluentd
  template:
    metadata:
      labels:
        app: eio-fluentd
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: elasticio
        image: elasticio/fluentd-kubernetes-gelf
        imagePullPolicy: IfNotPresent
        name: eio-fluentd
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: "/var/log"
          name: varlog
        - mountPath: "/var/lib/docker/containers"
          name: varlibdockercontainers
          readOnly: true
      serviceAccountName: eio-fluentd-account
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: "/var/log"
          type: ''
        name: varlog
      - hostPath:
          path: "/var/lib/docker/containers"
          type: ''
        name: varlibdockercontainers
  updateStrategy:
    type: OnDelete
