apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    component: api
    app: api
  annotations:
    deployment.kubernetes.io/revision: '2'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 'elasticio/api:{{ .Values.revision | default "master" }}'
        envFrom:
        - secretRef:
            name: elasticio
        env:
        - name: APP_NAME
          value: api
        - name: LOG_LEVEL
          value: info
        - name: PORT_API
          value: '9000'
        - name: MARATHON_URI
          value: http://mazafaka.io/this-env-var-is-deprecated-but-still-required-by-v1
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 3
          httpGet:
            port: 9000
            path: "/healthcheck"
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 3
          httpGet:
            port: 9000
            path: "/healthcheck"
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 0.5
          requests:
            memory: 256Mi
            cpu: 0.1
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: false
      imagePullSecrets:
      - name: elasticiodevops
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        elasticio-role: '{{ .Release.Namespace }}'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
