apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    component: api
    app: api-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: '9000'
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: api
  sessionAffinity: None
  type: NodePort
