replicas: 1
envFromSecretRefName: elasticio

image:
  tag: master
  pullPolicy: Always
  pullSecretName: elasticiodevops

resources:
  limits:
    memory: 2048Mi
    cpu: 1
  requests:
    memory: 512Mi
    cpu: 1

rbac:
  create: true

serviceAccount:
  create: true
  name: admiral-account
