apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    component: frontend
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 'elasticio/frontend:{{ .Values.revision | default "master" }}'
        envFrom:
        - secretRef:
            name: elasticio
        env:
        - name: APP_NAME
          value: frontend
        - name: PORT
          value: '8000'
        - name: LOG_LEVEL
          value: trace
        - name: ELASTICIO_API_URI
          valueFrom:
            secretKeyRef:
              name: elasticio
              key: API_URI
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 30
          httpGet:
            port: 8000
            path: "/backend/healthcheck"
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 3
          httpGet:
            port: 8000
            path: "/backend/healthcheck"
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 0.2
          requests:
            memory: 512Mi
            cpu: 0.1
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: false
      imagePullSecrets:
      - name: elasticiodevops
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        elasticio-role: '{{ .Release.Namespace }}'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
